### ISSUE TITLE
Incorrect Smotherwing Butterfly Sprite

### ISSUE THREAD

**Issue by KylieKat17** [SturmB/botw-armor-upgrade-tracker#2]
The sprite icon in the "Shopping List" displays that of a Fireproof Lizard instead of a Smotherwing Butterfly. I've attached a screenshot.

<img width="179" alt="ArmorTrackerScreenShot" src="https://github.com/SturmB/botw-armor-upgrade-tracker/assets/94423091/ab789fd9-c047-44f7-9511-2033c2b2d2ab">

**Comment by SturmB** [comment]
Excellent catch. I'll see about fixing that this afternoon.
